name: Build and Deploy Mail-Service

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package*.json'
      - 'Dockerfile'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          # 고유한 태그 사용 (최신 커밋 해시)
          docker build -t mail-service:${{ github.sha }} .

      - name: Update Kubernetes deployment
        run: |
          # 새 이미지로 디플로이먼트 업데이트
          kubectl set image deployment/mail-service mail-service=mail-service:${{ github.sha }}
          
          # 롤링 업데이트 전략 수정 (1개의 레플리카로도 업데이트가 가능하게)
          kubectl patch deployment mail-service -p '{"spec":{"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0}}}}'
          
          # 디플로이먼트 상태 확인 (타임아웃 설정)
          kubectl rollout status deployment/mail-service --timeout=180s